// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALDE646HOdb70h-gQS0KZiwnTHQhJ23Qk',
    appId: '1:719701894023:web:29b903e109161c441fe922',
    messagingSenderId: '719701894023',
    projectId: 'orbital-dis-connect',
    authDomain: 'orbital-dis-connect.firebaseapp.com',
    storageBucket: 'orbital-dis-connect.firebasestorage.app',
    measurementId: 'G-FT5GDG0R56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjN-oz0edeQmpGMmrvD_SwNSooAvpe1oI',
    appId: '1:719701894023:android:0c1bd615c0b21c361fe922',
    messagingSenderId: '719701894023',
    projectId: 'orbital-dis-connect',
    storageBucket: 'orbital-dis-connect.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqf5QKCQLD1ARbZhOXreczIg0fPT5uOAI',
    appId: '1:719701894023:ios:91ed7bcd1305ddfb1fe922',
    messagingSenderId: '719701894023',
    projectId: 'orbital-dis-connect',
    storageBucket: 'orbital-dis-connect.firebasestorage.app',
    iosBundleId: 'com.example.disconnectMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqf5QKCQLD1ARbZhOXreczIg0fPT5uOAI',
    appId: '1:719701894023:ios:91ed7bcd1305ddfb1fe922',
    messagingSenderId: '719701894023',
    projectId: 'orbital-dis-connect',
    storageBucket: 'orbital-dis-connect.firebasestorage.app',
    iosBundleId: 'com.example.disconnectMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALDE646HOdb70h-gQS0KZiwnTHQhJ23Qk',
    appId: '1:719701894023:web:79bbf2465425e8f01fe922',
    messagingSenderId: '719701894023',
    projectId: 'orbital-dis-connect',
    authDomain: 'orbital-dis-connect.firebaseapp.com',
    storageBucket: 'orbital-dis-connect.firebasestorage.app',
    measurementId: 'G-TDG7CBYDW8',
  );
}
